"""posts table

Revision ID: 231f447c0757
Revises: 16439c4c90ef
Create Date: 2018-12-25 15:56:56.414906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '231f447c0757'
down_revision = '16439c4c90ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('topic_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'topic_id')
    # ### end Alembic commands ###
